baseURL: 'https://web3story.github.io/OnChainMonkey/'
languageCode: 'en-us'
title: 'Web3Story'

Params:
    - copyright: 'Web3 Story'

# markup:
#     goldmark:
#         renderer:
#             unsafe: true
